"""empty message

Revision ID: 306d915bc6e0
Revises: 8a6946de90ad
Create Date: 2018-04-25 10:59:58.747679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306d915bc6e0'
down_revision = '8a6946de90ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additemmodel', sa.Column('Item_Deliver', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additemmodel', 'Item_Deliver')
    # ### end Alembic commands ###
