"""initial migration

Revision ID: 83f14917ad8a
Revises: 
Create Date: 2018-03-31 11:12:06.419609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f14917ad8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additemmodel', sa.Column('payment', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additemmodel', 'payment')
    # ### end Alembic commands ###
